[package]
name = "keysas-sign"
version = "1.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mbrman = "0.5.1" 
clap = { version = "4.0.32", default-features = false, features = ["std", "cargo"] }
minisign = "0.7.2"
anyhow = "*"
nom = "7"
libc = "*"
udev = "0.7.0"
