name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
        

    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - run: apt-get update -yq
    - run: |
        sudo apt -y install libyara-dev libyara9
        sudo apt-get install -y wget make lsb-release software-properties-common libseccomp-dev pkg-config git bash libudev-dev
    - run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run audit
      run: cargo audit --verbose
